### ISSUE TITLE
LXC 3.2.1 アナウンス翻訳

### ISSUE THREAD

**Issue by tenforward** [lxc-jp/linuxcontainers.org#10]

**Comment by tenforward** [comment]
とりあえず完成（見直しすらしてません）。またお時間のあるときにでもレビューお願いします！ @hnakamur https://github.com/lxc-jp/linuxcontainers.org/commit/ff5308f22b28500865c9024279a18d9890c4be46

**Comment by hnakamur** [comment]
確認しました。バッチリだと思います！ :+1:
いろいろ機能追加や改善されて興味深いリリースですね。

**Comment by tenforward** [comment]
レビューありがとうございます！
英語の typo は will のあとだから forwared -> forward かな :-)
