### ISSUE TITLE
OpenNebula 文書の翻訳

### ISSUE THREAD

**Issue by tenforward** [lxc-jp/linuxcontainers.org#4]
`getting-started-opennebula.md` という文書が追加されているので翻訳する

**Comment by tenforward** [comment]
https://github.com/lxc-jp/linuxcontainers.org/commit/f6e25240bcd6f90f3aea233a50d848f2b6f51f43

**Comment by tenforward** [comment]
"Final user" をとりあえず「最終的なユーザー」みたいに訳しているけど「通常使うユーザー」くらいにしたらいいのかな?

**Comment by hnakamur** [comment]
[Final user Synonyms, Final user Antonyms | Thesaurus.com](https://www.thesaurus.com/browse/final%20user) によると final user の類義語に end user があるそうなので、「エンドユーザー」でも良いかもですね。

あ、下の方には end users と書いてるところもあるんですね。単に言い換えてるという理解で良さそうな気もしますね。
